version: '3'
services:
  ollama-container:
    image: ollama/ollama
    container_name: ollama_container
    volumes:
      - ./data/ollama:/root/.ollama


    ports:
      - 11434:11434
  streamlit-app:
    image: test/ollama_test:v1
    ports:
      - 8501:8501